_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "TeacherStudentRCNN"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NUM_CLASSES: 8
  TEACHER_STUDENT:
    BASE_ARCH: "GeneralizedRCNN"
    WEIGHTS: "output/cityscapes_baseline/model_final.pth"
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
DATASETS:
  TRAIN: ("cityscapes_depth_train",)
  TRAIN_SOURCE: ("cityscapes_train",)
  TRAIN_TARGET: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_fine_instance_seg_val", "cityscapes_foggy_val")
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000,)
  MAX_ITER: 70000
  IMS_PER_BATCH_SOURCE: 4
  IMS_PER_BATCH_TARGET: 4
TEST:
  EVAL_PERIOD: 5000
