_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "ResnetDEB"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 8
  BACKBONE:
    NAME: "build_resnet_backbone"
INPUT:
  MIN_SIZE_TRAIN: (640,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
DATASETS:
  TRAIN: ("cityscapes_depth_train",)
  TEST: ("cityscapes_depth_val",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (30000,)
  MAX_ITER: 50000
  IMS_PER_BATCH: 2
TEST:
  EVAL_PERIOD: 1000
